### ISSUE TITLE
Convenience API suggestion: return an array

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-intl-segmenter#1]
E.g. `Intl.Segmenter.segments("string", "fr", { type: "word" })`

**Comment by mathiasbynens** [comment]
Shouldn’t this be an iterator so it can be done lazily? If you really need an array you could then use the spread operator.

**Comment by domenic** [comment]
The main API in the readme returns an iterator. The point of this convenience API is for when you know you need all the results.

**Comment by mathiasbynens** [comment]
Apologies; I had somehow interpreted your suggestion as “an array of strings: one for each segment”.

**Comment by domenic** [comment]
I guess I was ambiguous. Now that you mention it, as a convenience API, that sounds better to me.

**Comment by mathiasbynens** [comment]
#4

**Comment by littledan** [comment]
If we want something like this, maybe it should be a method on a Segmenter instance, e.g.,

```
new Intl.Segmenter("fr", {type: "word"}).segmentToArray("string"))
```

What should be the output exactly? Would you want just the words in this case, ignoring the whitespace and punctuation segments?

**Comment by domenic** [comment]
Yeah, just the words is what I was assuming.

A static method feels more convenient than newing up a new object, but I guess Intl has not gone with that style so far.

**Comment by domenic** [comment]
Closing since it doesn't fit with the style of Intl.
