### ISSUE TITLE
Provide a locale-less segmenter

### ISSUE THREAD

**Issue by Manishearth** [tc39/proposal-intl-segmenter#10]
We should have the ability to create a segmenter that does exactly what UAX 29 tells it to do, and nothing more.

**Comment by littledan** [comment]
I believe the general concept here is the "root locale", a synthetic locale which has the defaults of the Unicode algorithms and data tables. In general, ECMA 402 does not expose the root locale, if I understand correctly. Instead, it permits an implementation-dependent "default locale", which will typically be the User Agent's locale. The default locale is used if you pass `undefined` as the locale argument. There are other places where the root locale would show up, e.g., case conversion and collation. I'm not sure what went into that decision, but I'm just blindly following it. Cc some people who may know more about this: @NorbertLindenberg @caridy @jungshik @srl295

**Comment by NorbertLindenberg** [comment]
Before jumping to solutions, what's the use case that prompted this request? Which boundaries are needed for this use case? Does "exactly what UAX 29 tells it to do" include tailoring?

**Comment by Manishearth** [comment]
No, I was explicitly excluding tailoring.

The use case is being able to operate consistently in a locale-less environment, basically.

**Comment by NorbertLindenberg** [comment]
The default grapheme clusters are known to be broken for a number of Brahmic scripts. The default word boundaries are known to be broken for Chinese, Thai, and various other scripts. The default sentence boundaries are known to be inadequate even for English. So for which purposes would they actually be useful and produce desirable results without tailoring?

**Comment by Manishearth** [comment]
I am aware that they are broken. The reason is compatibility; a lot of ICU-based (or otherwise UAX 29-based) applications already rely on those boundaries, and you may want your code to be able to share a definition of grapheme boundaries.

**Comment by littledan** [comment]
We'll stick with the rest of ECMA 402 in not providing a root locale, as @NorbertLindenberg has explained clearly that such a locale is inherently broken.
