### ISSUE TITLE
Convenience API suggestion: return the length

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-intl-segmenter#2]
E.g. `Intl.Segmenter.count("string", "fr", { type: "grapheme" })` would be quite useful for e.g. a Twitter-style service limiting you to 140 chars.

**Comment by littledan** [comment]
Similar to #1, should this be a method on Segmenter instances, like `new Intl.Segmenter("fr", {type: "grapheme"}).count("string")`?

**Comment by domenic** [comment]
Unlike #1, I'll leave this open as I still think it's useful. Feel free to close as out of scope of "v1" if you want though.

Moving it to a method on instances makes sense from the perspective of fitting with the rest of Intl.

**Comment by littledan** [comment]
BTW one-liner for this, but maybe it's a little obscure: `[...new Intl.Segmenter("fr", { type: "grapheme" }).segment("string")].length`

**Comment by domenic** [comment]
I'm now recalling that the discussion for this was that we should not add "premature optimization" APIs without knowing if they're needed. I.e. I think allocating that iterable, spreading it, and taking its length sounds pretty expensive if you're e.g. updating a character counter in an editor. But thinking that something is pretty expensive, without measurement, is not reason for adding a new API.

So, feel even more free to close, I guess :)
