### ISSUE TITLE
Different word for the two different "types"?

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-intl-segmenter#3]
This is really minor, and aligning with existing APIs and vocabulary takes precendence IMO. But it might be worth considering whether we can use a different word (e.g. "kind") or some prefix ("segmentType") to disambiguate between the constructor option and the breakType.

**Comment by littledan** [comment]
@jungshik any advice on what is typical here for names?

**Comment by littledan** [comment]
Right, thanks for the suggestion here.
