### ISSUE TITLE
What is the prototype of %SegmentIteratorPrototype%?

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-intl-segmenter#34]
Does `%SegmentIteratorPrototype%` have a `[[Prototype]]` slot with value `%IteratorPrototype%`? I don't see any spec text that says this. Is this an oversight? 

Here's how the ECMA262 iterators specify this:
* https://tc39.github.io/ecma262/#sec-%setiteratorprototype%-object
* https://tc39.github.io/ecma262/#sec-%mapiteratorprototype%-object
* https://tc39.github.io/ecma262/#sec-%arrayiteratorprototype%-object
etc

**Comment by FrankYFTang** [comment]
@rwaldron @littledan

**Comment by FrankYFTang** [comment]
@Ms2ger
