### ISSUE TITLE
Intl.Segmenter constructor should coerce options to Object first

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-intl-segmenter#37]
In [Intl.Segmenter](https://tc39.github.io/proposal-intl-segmenter/#sec-Intl.Segmenter), we have:

```
5. Let matcher be ? GetOption(options, "localeMatcher", "string", « "lookup",  "best fit" », "best fit").
6. Set opt.[[localeMatcher]] to matcher.
7. Let lineBreakStyle be ? GetOption(options, "lineBreakStyle", "string", « "strict",  "normal", "loose" », "normal").
```

and then much later we have the coercion of the `options`  argument in to an `Object`:
```
11. If options is undefined, then
    a. Let options be ObjectCreate(null).
12. Else
    b. Let options be ? ToObject(options).
```

This is inconsistent with all the other intl objects. The coercion to `Object` should happen before properties of the `options` argument are accessed.

cc @FrankYFTang

**Comment by littledan** [comment]
Closing per #32
