### ISSUE TITLE
Convenience: method to get current token from iterator

### ISSUE THREAD

**Issue by inexorabletash** [tc39/proposal-intl-segmenter#4]
In every example I've written using this (like [this one](https://gist.github.com/inexorabletash/a279f03ab5610817c0540c83857e4295)) I end up with this pattern:

``` js
const words = [];
const iterator = Intl.Segmenter(locale, {type: 'word'}).segment(text);
let pos = iterator.index();
for (let {index, breakType} of iterator) {
  if (breakType !== 'none')
    words.push(text.slice(pos, index));
  pos = index;
}
```

i.e. I need to maintain `pos` tracking the previous index and slice the string myself. How about:

`%SegmentIterator%.prototype.segment`

Return a substring of the input string from last index to the current index.

...so you can just write:

``` js
const words = [];
const iterator = Intl.Segmenter(locale, {type: 'word'}).segment(text);
for (let {index, breakType} of iterator) {
  if (breakType !== 'none')
    words.push(iterator.segment());
}
```

**Comment by littledan** [comment]
Maybe the iterator should always be of the string slices, with the understanding that the iterator is an extra convenience thing, on top of the lower-level imperative API based on `advance` which gives you the index. Thoughts?

**Comment by inexorabletash** [comment]
The strings aren't useful without the type so you'd need a (substring, type) tuple of some sort.

**Comment by littledan** [comment]
The next method does this.
