### ISSUE TITLE
The invocation of ResolveLocale is missing an argument

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-intl-segmenter#58]
The current [specification of `Intl.Segmenter`](https://tc39.github.io/proposal-intl-segmenter/#sec-Intl.Segmenter) invokes [ResolveLocale](https://tc39.github.io/ecma402/#sec-resolvelocale) with only 4 arguments, omitting the mandatory _localeData_:
> Let <var>r</var> be <emu-xref aoid="ResolveLocale"><a href="https://tc39.github.io/ecma402/#sec-resolvelocale">ResolveLocale</a></emu-xref>(%Segmenter%.[[AvailableLocales]], <var>requestedLocales</var>, <var>opt</var>, %Segmenter%.[[RelevantExtensionKeys]]).

**Comment by FrankYFTang** [comment]
This Issue should be closed by #64 . Please close it.
