### ISSUE TITLE
Script runs

### ISSUE THREAD

**Issue by brawer** [tc39/proposal-intl-segmenter#66]
Would splitting text into script runs be in scope for the `Intl.Segmenter` API?

**Comment by littledan** [comment]
@brawer I'm wondering what use case you have in mind here. We have a long way to go if we wanted to expose the data necessary for font/glyph selection, which would be a major application of splitting text into script runs. Overall, I was thinking that we'd leave splitting by script runs out of scope.

**Comment by gibson042** [comment]
Agreed; changes in script will be reflected in segments only to the extent that underlying processing detects them as boundaries.
