### ISSUE TITLE
Consider removing the locale from grapheme segmentation

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-intl-segmenter#7]
A strong piece of feedback from the September 2016 TC39 meeting (from @bterlson, @rniwa and others) was that the locale is not needed for grapheme breaks, so it should not be a parameter. However, I later spoke with Mark Davis, who said that logic for "extended grapheme clusters", e.g., for Indic scripts, is still in flux, and he recommended that all new APIs for grapheme segmentation take a locale as a parameter for future-proofing.

**Comment by rniwa** [comment]
Not sure who you were trying to tag, but I've never attended a TC39 meeting.

**Comment by littledan** [comment]
@rniwa Sorry for the sloppy wording, you weren't at TC39 but I think you mentioned this on IRC at http://logs.glob.uno/?c=freenode%23whatwg&s=27+Sep+2016&e=29+Sep+2016#c1006562

**Comment by littledan** [comment]
In particular:

> \<rniwa_>	jyasskin: so my point was more that Grapheme clusters is more of a Unicode concept that doesn't depend on ICU

The feedback from Mark Davis was that, actually, extended grapheme clusters for Indic scripts, for one, may actually be more complex and locale-dependent than the plain old standard Unicode algorithm from UAX 29.

**Comment by rniwa** [comment]
> The feedback from Mark Davis was that, actually, extended grapheme clusters for Indic scripts, for one, may actually be more complex and locale-dependent than the plain old standard Unicode algorithm from UAX 29.

Oh, I wasn't aware of that. Do you have any pointers to any documentation about it?

**Comment by littledan** [comment]
See [this bug](http://unicode.org/cldr/trac/ticket/2142), and in particular [this CLDR wiki page](http://cldr.unicode.org/development/development-process/design-proposals/grapheme-usage). Seems like CLDR/ICU don't support this yet, but it's planned.

**Comment by bterlson** [comment]
Not sure if you're looking for validation here, but I'm convinced :-P
