### ISSUE TITLE
Rename Segment Iterator to Boundary Iterator

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-intl-segmenter#78]
* Segment Iterator → Boundary Iterator
* SegmentIterator* → BoundaryIterator*

cf. https://github.com/tc39/proposal-intl-segmenter/pull/67#discussion_r276965902
> Please, BoundaryIterator rather than BreakIterator. "Boundary" is better because it applies more generally (e.g., there are grapheme boundaries but not really grapheme breaks). It was also the predominant term recorded [in meeting notes](https://docs.google.com/document/d/1EXzr3ekK0AwYjoBMJDDTkZUZ5ST_5epgg0EFYASYq4c/edit):
> 
> > * RG: It sounds like there's a rough consensus over making this an iterator over the boundaries.
> > * FT: How about "boundaryType"?
> > * RG: It seems like we have an agreement on the conceptual model.  I'd like to follow up with a PR.  If you're breaking on words, for example, do you need to distinguish segments that are whitespace, for example, compared to a segment of letters?

**Comment by littledan** [comment]
This name isn't visible outside of the spec; I am fine with renaming it if you would like. PRs welcome.
