### ISSUE TITLE
Add an @@iterator method to the iterator prototype

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-intl-segmenter#79]
Without it, these objects don't actually implement the [Iterable interface](https://tc39.github.io/ecma262/#sec-iterable-interface) and for-of/`Array.from`/etc. won't properly consume them.

Based on the random access pattern, I think we just want a @@iterator that returns the receiver.

**Comment by littledan** [comment]
I was wondering about the same, but this is actually handled by the parent class, `%IteratorPrototype%`.
