### ISSUE TITLE
Notes from 2019-05-22 Deep Dive

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-segmenter#87]
We had a call with Mark Davis and Andy Heninger to discuss the architecture of Intl.Segmenter.  The notes are shown below.

-----

Attendees:

- Shane Carr (SC)
- Richard Gibson (RG)
- Daniel Ehrenberg (DE)
- Steven Loomis (SL)
- Mark Davis (MD)
- Andy Heninger (AH)
- Frank Tang (FT)

## Intl.Segmenter Sync

SC: [README](https://github.com/tc39/proposal-intl-segmenter). (discusses importance of the API)

DE: Other code point iterators in JavaScript may also follow this model in the future.

SC: Let's discuss [issue 80](https://github.com/tc39/proposal-intl-segmenter/issues/80), precedingSegmentType.  ICU seems to only return one status at a time; should we treat it as binary or an enum or a list?

AH: Multiple break types might happen more often in line break.

RG: The properties seem to be more applicable to the boundary itself, not the segment.

MD: Yeah.

AH: I'm guilty of the ICU API.  It's sometimes useful, but it's not carefully architecturally designed.

MD: THe thing it's useful for is, take words.  I can quickly determined that the segment I just passed over is spaces.  But sometimes it's not relevant and I don't care.

RG: We don't have evidence that it's possible to know you passed over spaces.  Because punctuation is the same status as space.

AH: Yeah.

MD: I wouldn't say it's an artifact, because it's based on the rules out of Unicode.  But various status things were attached to some of them.

SL: What rule broke is important for determining the overall flow. List of rule tags in ICU4C's [unicode/ubrk.h](http://icu-project.org/apiref/icu4c/ubrk_8h_source.html#l00144)

FT: ICU reports a vector, like kana range, numeric range, etc.  So currently, in the past, we considered all of them as words, rather than separate them.  But then we had a question on whether we should separate them.  So, are we talking about the last character?  The second question is, you can do a backwards search.  What is the status when you do backwards?

AH: For ICU, it's the thing preceding in the string.

MD: It's less useful going backwards.

AH: We did it that way deliberately, because it doesn't matter how you got to this boundary.

MD: If we were to standardize it, we may want to further collapse.  An interesting thing is, did I hit an alphanum in the last token.

AH: ICU gets funny there. When the dictionary comes into play, you don't get the status out of the rules.  If you have a jumbling of different scripts, there may have been other things at intermediate points.

SL: That's where maybe there was the expectation that the result would be the union of those tags, rather than the last one.

AH: I think to design something architecturally, you want to think about what you actually want it to do, and not look at what ICU does.

MD: You could iterate and return the index, and then think about if you also want to return information about the break.

AH: Question.  Why do we think boundaries are more useful than segments?

DE: I think the categories should definitely be in v1.  For word counting, and other operations on words, you really want to distinguish between words and spaces.  So that's why the current API has word/space, sentence/terminator.  At least binary distinction seemed very important for core use cases.  The question ended up being, how can we design the API so that v2 is not incongruous.

SL: Numbers are also important; they may be used or not used.

RG: We know that number information is not exposed by ICU.  You only get the number tag if you are definitely transitioning from a number to a non-number.  For example, "A113" is a number, but "113A" rule status is letter.  So ICU does not give you that information.

MD: The useful information would be, did I see a letter, did I see a number.  That would be the most useful stuff people would want to have.  You might also want to do, did I see whitespace.  But you might want to separate out word and number.

FT: So is the status based on just the last character?

MD: It's a state machine.

AH: The rules can encompass larger compass, but not always.

RG: The info coming back from ICU is specifically about the boundary, not the segment.

MD: Did I see a letter, did I see a number, both bits, would be useful but would require restructuring ICU.

FT: So we have a state machine.  Can you figure out what the previous token was, based on the state of the state machine?

AH: Usually, with hand-waiving.

MD: The states can give people the wrong expectations.

RG: So we're not bound on the specifics of implementation, but we're bound on the specifics of the interface exposed.  There's some back and forth.  What we're seeing as available to implementers through ICU, we could bucket whitespace and punctuation into one category, and everything else into another category.

MD: That's a question for AH.  Is there a status that means, I saw only whitespace and punctuation?

AH: I think that mostly counts.  But if you have "123." that might trigger number status.

RG: That sounds correct.

AH: So, ICU's word break rules do make that distinction possible.

SL: link to Unicode word break rules [UTR#29](https://www.unicode.org/reports/tr29/#WB9) - could the rules be structured in order to make the distinction

RG: The rules are invisible to an author using this API.  They are not exposed, and we don't want authors thinking about the rules.

AH: If you were to specify, this is a number-like or word-like thing, and rigorously define what that looked like, then if the rules were to surface that information, they would have to implement that.

RG: The most extreme version of that I can think of is that an author could feed in characters that they feel are relevant, that could trip flags in the internal state.

AH: That would be difficult for ICU to implement.  There's not a separate hook.

SC: Can we loop back to AH's question, segments vs. boundaries?

MD: I think both of them are useful.

AH: We're doing a lot of talk about the properties of the segment preceding. So you may as well talk about the properties of the segment.

MD: I think you might not want to force the API to return strings.

AH: Conceptually, it's not a boundary in isolation.  It's the region between the previous boundary and the current boundary.  So if you're thinking about boundaries, the first useful boundary is the second one.

MD: It seems you could have two APIs.  One returns the string, the other returns the properties.

AH: You could return the position and the length.

RG: One of the nice characteristics from our perspective is the idea of random access.  That you could say, find me a boundary that follows an arbitrary position that might not itself be a boundary.

MD: Random access is good.  You might want an API for a popular subcase: you just want to iterate over the segment strings.  It could be worth as a convenience to users.  But I absolutely think the boundary and random access API is useful.

AH: I'm not familiar enough with JavaScript conventions.

FT: When walking backwards, you don't actually know how far back the preceding segment goes.

AH: Random access is hard to implement.  You have to back up to a safe point, and then walk forward again.

FT: From the JavaScript API point of view, if you only return the type, what does that really mean to the caller of the API?  You have a preceding segment type, but you don't know where the segment starts.

MD: If I'm walking forward, it's useful to have this extra information.  If I'm doing random access, the extra information is not as useful.

AH: What actually happens under the hood is that it has to find the previous boundary anyway.

MD: Technically it's a safe point, which may not actually be a boundary.

SC: Can you elaborate on what you mean by "rigorously define … "?

MD: Look at UAX #29, and specify the types in terms of those [character classes](https://www.unicode.org/reports/tr29/#Table_Word_Break_Property_Values).  But the character classes can be supplemented over time.

AH: The word break doesn't carry a lot of context.  Words hand together, numbers hang together, words and numbers next to each other hang together.

RG: I don't see enough information for us to draw a distinction between numbers and words.  We could say, things that are number-like or word-like.  There's no clear path to me by which something else could be implemented.  And we don't mean *all* punctuation; we mean punctuation that resulted in a break following it.

AH: You have Hebrew stuff, etc., so punctuation is a hard case.

SL: Yeah, there's punctuation for the break rule.

MD: (shows TR29 such as [WB9](https://www.unicode.org/reports/tr29/#WB9) )

: should we make TR29 categories nomative?
RG: they can be tailored.  wordlike/non wordlike..

: what about Dictionary based? [[ cjk, lao, thai ]]

SC: We sometimes point to Unicode specs from the ECMAScript spec.  But my concern here is, I don't want to point to TR29 because it would lock in implementations for using a Unicode break engine.  Is there another way we can specify what we mean by segment types like number, word, and punctuation?  It seems like it would be elegant for the user to know what to expect.

MD: It's not easy unfortunately.  You could also end up doing unnecessary work.

SC: Okay, I can buy that argument for leaving the definition of word versus non-word as ILD.

FT: would it be easier to define as 'space or punctuation'?

RG: FT, are you talking about two categories or three?

FT: Two categories.

MD: If you have two categories, the definition of one defines the other.

AH: If you don't define it, you don't have portable behavior.

RG: I think that's ok.  Some implementations might have richer dictionaries, some might not.

DE: One thing we're deliberately vague about is the break iteration algorithm itself.  Because we don't know if Firefox will want to use the Unicode break algorithms.  So we've left that part of the specification open.

DE I wanted to make an API suggestion.  If we had a segment iterator, we could have isSpace(), and we could add more methods like that.

SC: Yeah, I was thinking of something like that which would be lazilly-computed getters.

SL: perhaps the word vs. number should be itself a tailoring - 'words, skipping numbers'  as a special tailoring?
MD: that gets tricky, because you want to know 'were there things between these two'

MD: One interesting thing if you have an API for "is X", then you could have an API that is, "what do you mean by X?"

FT: That sounds overkill.

MD: Well, if you wanted to be precise, you could do that.  And if that doesn't match what you need, you can look at the segment.

SL: But the meaning has to do with rules and context, not just the set of characters.

MD: You are returning the convex hull of what could possibly be in there.  It gives you as much info as possible without the internals.  But at this point, you would be better off saying, "this is a word-like thing, and a word-like thing *should* contain these characters," and leave the details up to the implementation.

SC: Thanks everyone.  We can discuss API details offline.  This has helped to point us in the right direction for the architecture design.

**Comment by zbraniecki** [comment]
Henri's post on segmentation includes the mention of this proposal and the complication it may bring - https://hsivonen.fi/string-length/
