### ISSUE TITLE
Method that returns only strings

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-segmenter#88]
I was thinking about the following pattern to convert a string to a list of grapheme clusters:

```
[...segmenter.segment(foo).map(x=>x.segment)]
```

This is an important feature of Segmenter, and maybe we should make this pattern easier, at least by adding an alternative to .segment that just returns strings.

**Comment by gibson042** [comment]
I'd rather not increase surface area and cognitive burden by introducing an interface that is a strict subset of another. `Array.from(segmenter.segment(str), o => o.segment)` and `for(let {segment} of segmenter.segment(str))` seem sufficiently easy.
